import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


BRAND_DARK = colors.HexColor("#0A2540")
BRAND_CYAN = colors.HexColor("#00D4AA")
TEXT_MUTED = colors.HexColor("#64748B")
TEXT_BODY = colors.HexColor("#1E293B")
BORDER_LIGHT = colors.HexColor("#E2E8F0")

DOC_TYPE_LABELS = {
    "project_status_report": "Project Status Report",
    "sprint_summary": "Sprint Summary",
    "meeting_minutes": "Meeting Minutes",
    "leave_application_letter": "Leave Application",
    "experience_certificate": "Experience Certificate",
    "expense_summary": "Expense Claim Summary",
    "onboarding_checklist": "Onboarding Checklist",
    "offboarding_checklist": "Offboarding Checklist",
}


def generate_pdf(
    doc_type: str,
    title: str,
    content: str,
    generated_by: str = "Centriq AI",
    thread_id: str = "",
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    org_style = ParagraphStyle(
        "OrgName",
        parent=styles["Normal"],
        fontSize=14,
        fontName="Helvetica-Bold",
        textColor=BRAND_DARK,
    )
    tag_style = ParagraphStyle(
        "Tag",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica-Bold",
        textColor=BRAND_CYAN,
        alignment=2,
    )
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontSize=22,
        fontName="Helvetica-Bold",
        textColor=BRAND_DARK,
        spaceAfter=0.2 * cm,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica",
        textColor=TEXT_MUTED,
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Normal"],
        fontSize=12,
        fontName="Helvetica-Bold",
        textColor=BRAND_DARK,
        spaceBefore=0.5 * cm,
        spaceAfter=0.2 * cm,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=TEXT_BODY,
        leading=16,
        spaceAfter=0.15 * cm,
    )
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica",
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
    )

    story = []
    doc_label = DOC_TYPE_LABELS.get(doc_type, "Document")
    now = datetime.now().strftime("%B %d, %Y %I:%M %p")

    header_table = Table(
        [[Paragraph("Aligned Automation", org_style), Paragraph(doc_label, tag_style)]],
        colWidths=["60%", "40%"],
    )
    header_table.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
    story.append(header_table)
    story.append(Spacer(1, 0.3 * cm))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_CYAN, spaceAfter=0.4 * cm))
    story.append(Paragraph(_escape(title), title_style))

    meta_parts = [f"Generated: {now}", f"By: {generated_by}"]
    if thread_id:
        meta_parts.append(f"Ref: {thread_id[:8]}")
    story.append(Paragraph("  |  ".join(meta_parts), meta_style))
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=0.5 * cm))

    _render_content(story, content, section_style, body_style)

    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=0.3 * cm))
    story.append(
        Paragraph(
            "Generated by Centriq AI | Aligned Automation | Confidential",
            footer_style,
        )
    )

    doc.build(story)
    return buffer.getvalue()


def _render_content(story, content: str, section_style, body_style):
    lines = [line.strip() for line in content.strip().splitlines() if line.strip()]
    pending_section = None
    pending_lines = []

    def flush():
        if pending_section:
            story.append(Paragraph(_escape(pending_section), section_style))
        for line in pending_lines:
            story.append(Paragraph(_escape(line), body_style))

    for line in lines:
        is_header = (
            (line.endswith(":") and len(line) < 60 and not line.startswith("http"))
            or line.startswith("#")
            or (line.isupper() and len(line) > 3)
        )
        if is_header:
            flush()
            pending_section = line.lstrip("#").rstrip(":").strip()
            pending_lines = []
        elif line.startswith(("- ", "* ")):
            pending_lines.append(f"- {line[2:].strip()}")
        else:
            pending_lines.append(line)

    flush()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
