services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: centriq
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - centriq-network
    volumes:
      - ./init-langfuse.sql:/docker-entrypoint-initdb.d/init-langfuse.sql

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    networks:
      - centriq-network
    volumes:
      - redis_data:/data

  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/langfuse
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3003
      - TELEMETRY_ENABLED=false
    networks:

      - centriq-network

volumes:
  redis_data:

networks:
  centriq-network:
    driver: bridge
