"""Generate the routing golden snapshot from REAL traffic (ai_request_logs).

Phase 0 harness growth: hand-written cases (routing_cases.py) only cover the edge
cases we could read from code comments. This script samples actual user messages
and snapshots what the *current* deterministic keyword router does with each, into
tests/routing_golden.json. The golden test (test_routing_golden.py) then asserts that
output never changes — a characterization test that lets Phase 2 refactor the routing
layer with proof it preserved real-world behavior.

This is a one-off / on-demand generator (needs the DB). The resulting JSON is the
artifact that lives in version control and is asserted offline.

    python -m tests.gen_routing_golden            # regenerate the golden

Notes:
- Emails are redacted to <email> for fixture hygiene (they don't affect keyword routing).
- Messages are normalised (whitespace collapsed) and deduped; the stored text is exactly
  what the test re-runs, so the snapshot is reproducible.
- The snapshot captures CURRENT behavior, bugs included — that's the point of a
  characterization test. Genuine bugs are flagged separately, not "fixed" by editing the
  golden.
"""

import json
import os
import re

from app.database import SessionLocal
from app.models import AiRequestLog
from app.agent import _try_keyword_route

_EMAIL_RE = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
_WS_RE = re.compile(r"\s+")
_GOLDEN_PATH = os.path.join(os.path.dirname(__file__), "routing_golden.json")
_MAX_LEN = 240
_MAX_ENTRIES = 400


def _clean(msg: str) -> str:
    msg = _EMAIL_RE.sub("<email>", msg or "")
    msg = _WS_RE.sub(" ", msg).strip()
    return msg[:_MAX_LEN]


def generate() -> dict:
    db = SessionLocal()
    try:
        rows = (db.query(AiRequestLog.user_message, AiRequestLog.domain, AiRequestLog.sub_intent)
                .filter(AiRequestLog.user_message.isnot(None), AiRequestLog.user_message != "")
                .order_by(AiRequestLog.created_at.desc())
                .limit(2000).all())
    finally:
        db.close()

    seen = set()
    entries = []
    matched = fell_through = 0
    disagreements = []  # keyword domain != logged domain (informational only)

    for user_message, logged_domain, logged_sub in rows:
        msg = _clean(user_message)
        key = msg.lower()
        if not msg or key in seen:
            continue
        seen.add(key)

        route = _try_keyword_route(msg)
        if route is None:
            fell_through += 1
            entry = {"message": msg, "domain": None, "sub_intent": None}
        else:
            matched += 1
            entry = {"message": msg, "domain": route["domain"], "sub_intent": route.get("sub_intent")}
            # informational: keyword layer routes somewhere the live pipeline did not
            if logged_domain and route["domain"].lower() != str(logged_domain).lower():
                disagreements.append((msg, route["domain"], logged_domain))
        entries.append(entry)
        if len(entries) >= _MAX_ENTRIES:
            break

    payload = {
        "_comment": "Auto-generated by tests/gen_routing_golden.py from ai_request_logs. "
                    "Characterization snapshot of _try_keyword_route on real messages. "
                    "Do not hand-edit; regenerate. See test_routing_golden.py.",
        "entries": entries,
    }
    with open(_GOLDEN_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

    print(f"wrote {len(entries)} entries -> {_GOLDEN_PATH}")
    print(f"  keyword-matched: {matched}   fell-through (defer to semantic/LLM): {fell_through}")
    if disagreements:
        print(f"  NOTE: {len(disagreements)} message(s) where the keyword layer disagrees with the "
              f"logged served domain (review for precedence bugs — NOT asserted):")
        for msg, kw, logged in disagreements[:15]:
            print(f"    - {msg!r}: keyword={kw} logged={logged}")
    return payload


if __name__ == "__main__":
    generate()
