apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: centriq
      sslmode: 'disable'
      postgresVersion: 1300 # minimum version for vector support usually
      timescaledb: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
