apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    access: proxy
    url: ${GRAFANA_POSTGRES_HOST}
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      sslmode: 'disable'
      postgresVersion: 1300
      timescaledb: false

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
