/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTeamRouteImport } from './routes/_layout.team'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutProjectUpdateRouteImport } from './routes/_layout.project-update'
import { Route as LayoutMyRequestsRouteImport } from './routes/_layout.my-requests'
import { Route as LayoutMyLibraryRouteImport } from './routes/_layout.my-library'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout.documents'
import { Route as LayoutControlHubRouteImport } from './routes/_layout.control-hub'
import { Route as LayoutBooksRouteImport } from './routes/_layout.books'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectUpdateRoute = LayoutProjectUpdateRouteImport.update({
  id: '/project-update',
  path: '/project-update',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyRequestsRoute = LayoutMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyLibraryRoute = LayoutMyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutControlHubRoute = LayoutControlHubRouteImport.update({
  id: '/control-hub',
  path: '/control-hub',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBooksRoute = LayoutBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/books': typeof LayoutBooksRoute
  '/control-hub': typeof LayoutControlHubRoute
  '/documents': typeof LayoutDocumentsRoute
  '/my-library': typeof LayoutMyLibraryRoute
  '/my-requests': typeof LayoutMyRequestsRoute
  '/project-update': typeof LayoutProjectUpdateRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
}
export interface FileRoutesByTo {
  '/books': typeof LayoutBooksRoute
  '/control-hub': typeof LayoutControlHubRoute
  '/documents': typeof LayoutDocumentsRoute
  '/my-library': typeof LayoutMyLibraryRoute
  '/my-requests': typeof LayoutMyRequestsRoute
  '/project-update': typeof LayoutProjectUpdateRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/books': typeof LayoutBooksRoute
  '/_layout/control-hub': typeof LayoutControlHubRoute
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/my-library': typeof LayoutMyLibraryRoute
  '/_layout/my-requests': typeof LayoutMyRequestsRoute
  '/_layout/project-update': typeof LayoutProjectUpdateRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/control-hub'
    | '/documents'
    | '/my-library'
    | '/my-requests'
    | '/project-update'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/books'
    | '/control-hub'
    | '/documents'
    | '/my-library'
    | '/my-requests'
    | '/project-update'
    | '/settings'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/books'
    | '/_layout/control-hub'
    | '/_layout/documents'
    | '/_layout/my-library'
    | '/_layout/my-requests'
    | '/_layout/project-update'
    | '/_layout/settings'
    | '/_layout/team'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/project-update': {
      id: '/_layout/project-update'
      path: '/project-update'
      fullPath: '/project-update'
      preLoaderRoute: typeof LayoutProjectUpdateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-requests': {
      id: '/_layout/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof LayoutMyRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-library': {
      id: '/_layout/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof LayoutMyLibraryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/control-hub': {
      id: '/_layout/control-hub'
      path: '/control-hub'
      fullPath: '/control-hub'
      preLoaderRoute: typeof LayoutControlHubRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/books': {
      id: '/_layout/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof LayoutBooksRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBooksRoute: typeof LayoutBooksRoute
  LayoutControlHubRoute: typeof LayoutControlHubRoute
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutMyLibraryRoute: typeof LayoutMyLibraryRoute
  LayoutMyRequestsRoute: typeof LayoutMyRequestsRoute
  LayoutProjectUpdateRoute: typeof LayoutProjectUpdateRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBooksRoute: LayoutBooksRoute,
  LayoutControlHubRoute: LayoutControlHubRoute,
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutMyLibraryRoute: LayoutMyLibraryRoute,
  LayoutMyRequestsRoute: LayoutMyRequestsRoute,
  LayoutProjectUpdateRoute: LayoutProjectUpdateRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
