/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTeamRouteImport } from './routes/_layout.team'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutConfigRouteImport } from './routes/_layout.config'
import { Route as LayoutAdminRouteImport } from './routes/_layout.admin'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigRoute = LayoutConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof LayoutAdminRoute
  '/config': typeof LayoutConfigRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
}
export interface FileRoutesByTo {
  '/admin': typeof LayoutAdminRoute
  '/config': typeof LayoutConfigRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/config': typeof LayoutConfigRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/config' | '/settings' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/config' | '/settings' | '/team' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/admin'
    | '/_layout/config'
    | '/_layout/settings'
    | '/_layout/team'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config': {
      id: '/_layout/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof LayoutConfigRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutConfigRoute: typeof LayoutConfigRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutConfigRoute: LayoutConfigRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
